---
- name: show version
  hosts: router
  gather_facts: False
  tasks:
    - name: show information
      ios_command:
        commands:
          - show version
      register: data
    - debug: var=data.stdout_lines







