---
- name: Dictionary playbook example
  hosts: router
  tasks:

    - name: Create and Add items to dictionary
      set_fact: 
          userdata: "{{ userdata | default({}) | combine ({ item.key : item.value }) }}"
      with_items:
        - { 'key': 'Name' , 'value': 'Aman'}
        - { 'key': 'Email' , 'value': 'aman@123.com'}
        - { 'key': 'Location' , 'value': 'Agra'}
        - { 'key': 'Nationality' , 'value': 'Indian'}

    -  name: Display the Dictionary
       debug: var=userdata