---
- name: Show current directory files
  hosts: router
  tasks:
    - name: Get list of files in current directory
      command: ls .
      register: result

    - name: Print list of files
      block:
        - debug:
            msg: "Files: {{ result.stdout_lines }}"
      rescue:
        - debug:
            msg: "Failed to get list of files: {{ result.stderr }}"
